// Generates src/static-assets.js from public/ so the Worker can serve its own static files
// when it is deployed without the Workers Assets binding (e.g. via a plain API script upload).
// With [assets] in wrangler.toml, matching files are served by Assets before the Worker runs,
// so this fallback is never reached there. Run after editing anything in public/:
//   node scripts/inline-assets.mjs
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { extname, join } from "node:path";

const TYPES = { ".css": "text/css; charset=utf-8", ".svg": "image/svg+xml" };
const dir = new URL("../public/", import.meta.url).pathname;
const entries = readdirSync(dir)
  .filter((f) => TYPES[extname(f)])
  .sort()
  .map((f) => {
    const body = readFileSync(join(dir, f), "utf8");
    const etag = `"${createHash("sha256").update(body).digest("hex").slice(0, 32)}"`;
    return `  ${JSON.stringify("/" + f)}: {\n    type: ${JSON.stringify(TYPES[extname(f)])},\n    etag: ${JSON.stringify(etag)},\n    body: ${JSON.stringify(body)},\n  },`;
  });
const out = `// GENERATED by scripts/inline-assets.mjs from public/. Do not edit by hand.\nexport const STATIC_ASSETS = {\n${entries.join("\n")}\n};\n`;
writeFileSync(new URL("../src/static-assets.js", import.meta.url), out);
console.log(`wrote src/static-assets.js (${entries.length} files)`);
